"""
Orchestra DSL - Code Generator

Generates executable Python code from AST.
"""

from typing import List
from orchestra_ast import *


class CodeGenerator:
    """Generate Python code from Orchestra AST"""
    
    def __init__(self):
        self.indent_level = 0
        self.generated_code = []
    
    def emit(self, code: str):
        """Emit a line of code with proper indentation"""
        indent = "    " * self.indent_level
        self.generated_code.append(f"{indent}{code}")
    
    def indent(self):
        self.indent_level += 1
    
    def dedent(self):
        self.indent_level -= 1
    
    def generate(self, program: Program) -> str:
        """Generate complete Python code from program"""
        # Reset state
        self.indent_level = 0
        self.generated_code = []
        
        # Emit imports
        self.emit("# Generated by Orchestra DSL Compiler")
        self.emit("# DO NOT EDIT - This file is auto-generated")
        self.emit("")
        self.emit("from typing import Any, Dict, Optional")
        self.emit("import asyncio")
        self.emit("")
        self.emit("# Orchestra runtime imports")
        self.emit("try:")
        self.indent()
        self.emit("from orchestra.advanced import AgentRouter, ConditionalExecutor, ErrorHandler")
        self.emit("from orchestra.advanced import CircuitBreaker, RetryConfig, RetryStrategy")
        self.dedent()
        self.emit("except ImportError:")
        self.indent()
        self.emit("# Fallback for testing without full orchestra installation")
        self.emit("pass")
        self.dedent()
        self.emit("")
        self.emit("")
        
        # Generate each workflow as an async function
        for workflow in program.workflows:
            self.generate_workflow(workflow)
            self.emit("")
            self.emit("")
        
        return "\n".join(self.generated_code)
    
    def generate_workflow(self, workflow: Workflow):
        """Generate workflow function"""
        self.emit(f"async def {workflow.name}(input: Dict[str, Any], swarm) -> Any:")
        self.indent()
        
        # Docstring
        self.emit(f'"""Generated workflow: {workflow.name}"""')
        self.emit("")
        
        # Initialize variables
        self.emit("# Workflow variables")
        self.emit("result = None")
        self.emit("agent = None")
        self.emit("quality_gate = 'standard'")
        self.emit("task = None")
        self.emit("")
        
        # Generate statements
        for stmt in workflow.statements:
            self.generate_statement(stmt)
        
        # Return result
        self.emit("")
        self.emit("return result")
        
        self.dedent()
    
    def generate_statement(self, stmt: Statement):
        """Generate code for a statement"""
        if isinstance(stmt, AgentStatement):
            self.generate_agent_statement(stmt)
        elif isinstance(stmt, TaskStatement):
            self.generate_task_statement(stmt)
        elif isinstance(stmt, GuardStatement):
            self.generate_guard_statement(stmt)
        elif isinstance(stmt, QualityGateStatement):
            self.generate_quality_gate_statement(stmt)
        elif isinstance(stmt, TimeoutStatement):
            self.generate_timeout_statement(stmt)
        elif isinstance(stmt, ConditionalStatement):
            self.generate_conditional_statement(stmt)
        elif isinstance(stmt, TryStatement):
            self.generate_try_statement(stmt)
        elif isinstance(stmt, Assignment):
            self.generate_assignment(stmt)
        else:
            self.emit(f"# Unsupported statement: {stmt.__class__.__name__}")
    
    def generate_agent_statement(self, stmt: AgentStatement):
        """Generate agent selection code"""
        self.emit("# Agent selection")
        
        if isinstance(stmt.agent_spec, SimpleAgent):
            self.emit(f"agent = swarm.get_agent('{stmt.agent_spec.name}')")
        
        elif isinstance(stmt.agent_spec, BestForRouting):
            criteria_str = ", ".join(
                f"{k}={repr(v)}" for k, v in stmt.agent_spec.criteria.items()
            )
            self.emit("router = AgentRouter(swarm)")
            self.emit(f"agent = router.best_for({criteria_str})")
        
        elif isinstance(stmt.agent_spec, CascadeRouting):
            agents_str = ", ".join(f"'{ref.name}'" for ref in stmt.agent_spec.agents)
            self.emit("router = AgentRouter(swarm)")
            self.emit(f"agent = router.cascade([{agents_str}])")
        
        elif isinstance(stmt.agent_spec, RoundRobinRouting):
            agents_str = ", ".join(f"'{name}'" for name in stmt.agent_spec.agents)
            self.emit("router = AgentRouter(swarm)")
            self.emit(f"agent = router.round_robin([{agents_str}])")
        
        else:
            self.emit(f"# TODO: {stmt.agent_spec.__class__.__name__}")
        
        self.emit("")
    
    def generate_task_statement(self, stmt: TaskStatement):
        """Generate task execution code"""
        self.emit("# Task execution")
        
        # Handle string interpolation ${variable}
        task_str = stmt.task
        if "${" in task_str:
            # Simple string interpolation using f-string
            task_str = task_str.replace("${", "{")
            self.emit(f"task = f\"{task_str}\"")
        else:
            self.emit(f"task = {repr(task_str)}")
        
        self.emit("if agent:")
        self.indent()
        self.emit("result = await agent.execute(task, quality_gate=quality_gate)")
        self.dedent()
        self.emit("else:")
        self.indent()
        self.emit("raise RuntimeError('No agent selected')")
        self.dedent()
        self.emit("")
    
    def generate_guard_statement(self, stmt: GuardStatement):
        """Generate guard clause validation"""
        self.emit("# Guard clause")
        condition_str = self.generate_expression_inline(stmt.condition)
        self.emit(f"if not ({condition_str}):")
        self.indent()
        self.emit(f"raise ValueError(f'Guard failed: {condition_str}')")
        self.dedent()
        self.emit("")
    
    def generate_quality_gate_statement(self, stmt: QualityGateStatement):
        """Generate quality gate setting"""
        self.emit(f"quality_gate = '{stmt.level}'")
        self.emit("")
    
    def generate_timeout_statement(self, stmt: TimeoutStatement):
        """Generate timeout setting"""
        self.emit(f"timeout = {stmt.seconds}")
        self.emit("")
    
    def generate_conditional_statement(self, stmt: ConditionalStatement):
        """Generate if-else statement"""
        condition_str = self.generate_expression_inline(stmt.condition)
        
        self.emit(f"if {condition_str}:")
        self.indent()
        for s in stmt.then_branch:
            self.generate_statement(s)
        self.dedent()
        
        if stmt.else_branch:
            self.emit("else:")
            self.indent()
            for s in stmt.else_branch:
                self.generate_statement(s)
            self.dedent()
        
        self.emit("")
    
    def generate_try_statement(self, stmt: TryStatement):
        """Generate try-catch-retry block"""
        self.emit("try:")
        self.indent()
        for s in stmt.try_block:
            self.generate_statement(s)
        self.dedent()
        
        for catch in stmt.catch_blocks:
            self.emit(f"except Exception as e:  # {catch.error_type}")
            self.indent()
            for s in catch.statements:
                self.generate_statement(s)
            self.dedent()
        
        self.emit("")
    
    def generate_assignment(self, stmt: Assignment):
        """Generate variable assignment"""
        value_str = self.generate_expression_inline(stmt.value)
        self.emit(f"{stmt.target} = {value_str}")
        self.emit("")
    
    def generate_expression_inline(self, expr: Expression) -> str:
        """Generate expression as inline Python code"""
        if isinstance(expr, Literal):
            return repr(expr.value)
        
        elif isinstance(expr, Identifier):
            return expr.full_name()
        
        elif isinstance(expr, BinaryOp):
            left = self.generate_expression_inline(expr.left)
            right = self.generate_expression_inline(expr.right)
            return f"({left} {expr.operator} {right})"
        
        elif isinstance(expr, UnaryOp):
            operand = self.generate_expression_inline(expr.operand)
            return f"({expr.operator} {operand})"
        
        else:
            return f"# Unsupported expression: {expr.__class__.__name__}"


# ============================================================================
# Testing
# ============================================================================

if __name__ == "__main__":
    from orchestra_lexer import Lexer
    from orchestra_parser import Parser
    
    test_source = """
    workflow credit_analysis {
        agent: best_for(complexity: high, max_cost: 0.01)
        
        guard: input.amount > 0
        
        if input.amount > 1000000 {
            quality_gate: strict
        } else {
            quality_gate: standard
        }
        
        task: "Analyze credit risk for ${input.company}"
    }
    """
    
    # Compile
    lexer = Lexer(test_source)
    tokens = lexer.tokenize()
    
    parser = Parser(tokens)
    ast = parser.parse()
    
    generator = CodeGenerator()
    code = generator.generate(ast)
    
    print("=" * 60)
    print("CODE GENERATOR TEST")
    print("=" * 60)
    print(code)
